### ISSUE TITLE
Chapter 18 issue

### ISSUE THREAD

**Issue by larryjcai** [mi-ael/genki_anki_deck_generator#11]
お疲れ様(でした): You must be tired after working so hard. (greeting between friends and coworkers) -> You must be tired after working so hard. (ritualistic expression)

**Comment by mi-ael** [comment]
Yes, I'm definitely tired. :sleepy: 

![image](https://user-images.githubusercontent.com/12199265/139747737-72f80fb4-1c49-48b0-aa24-2e571a298827.png)

I'm using the Genki II book (3rd edition) as a source for this deck. 
Disclaimer: I'm not a japanese native speaker, so I'm gonna trust Genki on this one.

But still, thanks for your report! If you find any more mistakes, feel free to report them.
