### ISSUE TITLE
Just a few typos

### ISSUE THREAD

**Issue by larryjcai** [mi-ael/genki_anki_deck_generator#12]
Chapter 15:
Kanji Typo: もう一度う->もう一度
Hiragana Typo: もういちどう->もういちど

Chapter 18:
Hiragana Typo (後)：おと->あと

Chapter 19:
Definition Typo (いらっしゃる): いろ -> いる

Chapter 20:
～見たいなX（rare）I'm not actually sure about this one, but I don't think you can use kanji with this word.
English Typo: to convery message (person に)->to convey message (person に)

Chapter 21:
Hiragana Typo (time of …; when…): こる -> ころ

Chapter 22:
Kanji Typo (to win (～に)): 勝->勝つ

**Comment by mi-ael** [comment]
Thank you! Sorry for the wait. I'll publish the changes on ankidecks in a few minutes
