### ISSUE TITLE
Modifying Card Generation Logic

### ISSUE THREAD

**Issue by neonrights** [mi-ael/genki_anki_deck_generator#19]
First thanks for creating this!

Not really an issue, but I was planning on forking this repo to modify the card generation logic and was wondering if I could get some help?

Basically, I wanted to modify your logic to potentially create three cards per template instead of two, i.e.
- kanji only -> english and hiragana
- hiragana -> english and kanji
- english -> kanji and hiragana

The reason being I'm already familiar with a good amount of kanji since I'm Chinese, so I'm often able "cheat" at guessing meaning by looking at the kanji. However, this doesn't help me in learning how to actually pronounce the words. For templates without kanji, the current logic will suffice.

Unfortunately, I'm completely new to anki's API, so I'm curious how it interacts with custom templates, e.g. do you create two cards for each template or does anki support custom logic when displaying custom templates? If you could give me any pointers to docs or your code logic that would save me a huge amount of time. :)

**Comment by mi-ael** [comment]
I kind of forgot this repo even existed for the last year :sweat: 

If you are still interested in some pointers after all this time, I'll gladly help you.
