### ISSUE TITLE
Genki L04 Issue

### ISSUE THREAD

**Issue by redinou** [mi-ael/genki_anki_deck_generator#2]
![bug](https://user-images.githubusercontent.com/86521356/123513178-441fd800-d6be-11eb-8ef5-74b010931db1.PNG)

The audio for this word is wrong, it's says "毎週（まいしゅう）instead of "あさって"

Thank you for your hard work on this deck, its very helpful!

**Comment by JonasBurger** [comment]
thanks for the feedback.

This was already fixed with the pull request https://github.com/mi-ael/genki_anki_deck_generator/pull/1

I already updated the version on anki-decks on 2021-05-14. You just have to update your deck with the newest version.

**Comment by redinou** [comment]
Ho my bad!
Sorry

**Comment by mi-ael** [comment]
no problem :D
