### ISSUE TITLE
Latest build has missing audio

### ISSUE THREAD

**Issue by supertrianguloid** [mi-ael/genki_anki_deck_generator#20]
It looks like the latest build on ankiweb is missing audio files for many notes, for example the first example on the ankiweb page (Genki 1::L00::02 Numbers 0-100_10)  has missing audio. I built the deck myself locally, supplying my own audio files and didn't have this problem. This may be because the google drive links in `download_genki_sound_files.py` have expired.

Thank you for the project!

**Comment by mi-ael** [comment]
Thanks for telling me about this quite severe bug and sorry for replying so late.
I have regenerated the packages and uploaded them to ankidecks ( https://ankiweb.net/shared/info/1742947823 ).
I tested it on my machine and the sound files for "Genki 1::L00::02 Numbers 0-100_10" worked, but I would thank you if you could test it on your side as well.
