### ISSUE TITLE
"Anki could not find the line between the question and the answer"

### ISSUE THREAD

**Issue by chilllion** [mi-ael/genki_anki_deck_generator#21]
Hello!
I'm super keen to use your deck but I've encountered a problem. I want to flip the deck so the english is on the front side of the flashcard, yet when I go edit>cards>flip> it comes up with the error message: "Anki could not find the line between the question and the answer. Please adjust the template manually to switch the question and the answer". I've looked on many subreddits and forums but nothing has solved my issue. I am using macOS. Do you know how I can fix this issue so I can flip the cards? I have noticed this issue only happens on this deck. Thank you
<img width="1070" alt="Screenshot 2023-07-20 at 4 00 57 pm" src="https://github.com/mi-ael/genki_anki_deck_generator/assets/140046013/c218292f-9c45-41e9-b591-a7b4861e2c0d">
<img width="1073" alt="Screenshot 2023-07-20 at 4 01 16 pm" src="https://github.com/mi-ael/genki_anki_deck_generator/assets/140046013/1d104a0a-1bc5-47f7-bcc2-e39033e5bb90">

**Comment by mi-ael** [comment]
Sorry, but I don't use MacOS and sadly can't help you with that problem in particular.

There are a few of decisions I made when creating this deck that could cause this problem. In hindsight I should have not used a 3rd party tool to create the deck, but the REST-Api-Plugin for Anki. But I have no plans fixing that now.
