### ISSUE TITLE
crash on import of anki droid

### ISSUE THREAD

**Issue by schoettner** [mi-ael/genki_anki_deck_generator#22]
Hi,
I used and loved your Genki decks and wanted to create an own custom deck using your style. To create it, i mostly used the anki_exporter.py. After a few tries I was able to create a deck including my audio etc. I verify that it is working fine on the Anki Windows client. However, when I want to import the deck in AnkiDroid, it just crashes. I connected the phone with ADB but the logs only print a more or less useless 
`java.lang.RuntimeException: An error occurred while executing doInBackground()`
error. Anyone experienced this before and has a clue, what might cause this?

**Comment by mi-ael** [comment]
Sorry, but I haven't experienced that error before and have no clue what might cause it.

If I would start this project all over again I would probably use the API exposed by the Anki Connect Plugin ( https://ankiweb.net/shared/info/2055492159 ). I personally had a better experience with that, than using genanki.
