### ISSUE TITLE
Lesson 5 - 天気 audio is wrong

### ISSUE THREAD

**Issue by SilverBzH** [mi-ael/genki_anki_deck_generator#26]
Hi,

The audio attached to 天気 is incorrect. It supposed to be てんき and what I heard is げんき.

I fetched the deck from https://ankiweb.net/shared/info/1742947823

Thanks

**Comment by golddragon007** [comment]
I don't have that issue...

**Comment by SilverBzH** [comment]
I just listen to the audio attached to 天気 and I do hear the right sound as well. I guess I miss heard, thanks for double checking.
