### ISSUE TITLE
Incorrect hiragana on a couple of Genki II cards

### ISSUE THREAD

**Issue by floor3054** [mi-ael/genki_anki_deck_generator#5]
Hello, I see Genki 2 is WIP but thought I'd raise an issue just in case. There were a couple of cards where the text was お rather than あ. For example しおわせ(な) rather than the audio and text book しあわせ(な). Sorry I didn't make a note of the other one. Hope it helps. I'll get a note of the other one if it does.

**Comment by mi-ael** [comment]
Thank you for the bug report. I fixed the issue for しあわせ and あむ in L13. 
Most likely there are more typos or bugs in the deck (it's quite new) and reports like these are very welcome.
I'll publish the fixes to ankidecks in a few minutes.
