### ISSUE TITLE
Found a few minor mistakes

### ISSUE THREAD

**Issue by Drakkanrider** [mi-ael/genki_anki_deck_generator#6]
Wrong audio in おおきさ and ファイル
ボランテイア should be ボランティア
しょうかくきん should be しょうがくきん
たのしみたい should be たのしみです
かんこう should be かんこうする

Thanks for making this deck! I'll report if I find any issues in the later lessons.

**Comment by mi-ael** [comment]
Thanks! I fixed them.
I'll publish the fixes on ankidecks in a few minutes.

> I'll report if I find any issues in the later lessons.
perfect :D
