### ISSUE TITLE
Pile of random issues, mostly typos, some missing data

### ISSUE THREAD

**Issue by Drakkanrider** [mi-ael/genki_anki_deck_generator#7]
Kanji issues:
いますぐ looks like it's actually supposed to be ちゅうもんする (has all the audio, kanji, etc. for the latter, and there's a different card with all the stuff for いますぐ)
こんなふう: kanji representation こんな風に should just be こんな風 (drop the に)
じしょ: kanji representation of 字書 should probably be 辞書. They both mean dictionary, but the latter is the one used in the textbook. I think 字書 specifically refers to kanji dictionaries usually or something like that.
いなくなる seems to be missing its kanji representation (it just has '（rare）' in the kanji field)
けんこう and りそう are both entirely missing their kanji representations
るそばん missing kanji representation (also should be るすばん, noted that below as well)
そんな～ has the kanji and kanji meanings for 戻ってくる listed
たのしみです: kanji representation still needs to be changed from 楽しみたい to 楽しみです
かんこうする: ditto for this one, kanji representation still needs to be changed from 観光 to 観光する

Note: the cards I've reported with missing kanji representations are all ones that have kanji listed in the textbook vocab list, not just ones that happen to not have kanji.

Typos in Hiragana:
いまでに -> いますぐ
おゆかわく -> おゆがわく
ごせんちゅう -> ごぜんちゅう
ごらんいなる-> ごらんになる
しょろい -> しょるい
せいがく -> せいかく
ほにゃくする -> ほんやくする
むだｄずかい -> むだづかい
よろしくあったえください -> よろしくおつたえください
ふくる -> ふくろ
るそばん -> るすばん

Minor typos in the English translations (are these things you want reported if I spot more, or just errors in the Japanese?):
おねがいする: requestion -> request
かじ: house work -> housework
こうはい: groups -> group
しょうしょう: second -> seconds
しりあう: acquanted -> acquainted
はれる: be come -> become
よしゅう: perperation -> preparation
バレンタインデー: Valantine’s -> Valentine's
がっかりする: dissapointed -> disappointed
はなれる: someonse -> someone & seperates -> separates

And this last one isn't a mistake, but just an inconsistency:
Most cards with a kanji representation that's rare are marked with (rare) following the kanji (e.g. '可哀相（rare）'), but the card あめがやむ has it marked like this（rare：雨が止む）instead. Not sure if that's something you care about, but just fyi

**Comment by mi-ael** [comment]
Thank you very much!
I fixed all of them (the last one too, it just looked weird)

If you spot more errors of any kind, just keep reporting them like you did here. The formatting made it really easy for me to find and fix them :+1: 

I'll publish the fix to ankidecks in a few minutes. Newer versions of this deck can be imported over older ones without loosing progress.
