### ISSUE TITLE
Spotted another handful of typos

### ISSUE THREAD

**Issue by Drakkanrider** [mi-ael/genki_anki_deck_generator#9]
Kanji issues:
ためる - Should probably be 貯める. This doesn't have kanji listed in the textbook, but 溜める means storing up in general, while 貯める specifically refers to saving money
こうかんする: 交換すする -> 交換する (also in the kanji_meaning field)
ゆうがた: 多方 -> 夕方

Hiragana typos:
シヤツ -> シャツ
ぎゅうがくせい -> ちゅうがくせい
おと (the one for 後) -> あと
おさきにしっれいします -> おさきにしつれいします
そだてう -> そだてる

English typos:
じゅんび: preperation -> preparation
する (the one for wearing items): watchy -> watch
おかげで: thank -> thanks
ひろう: pick -> pick up
まちがえる: mistake -> a mistake

And this is one I'm not sure you care about, but a bunch of the cards with kanji representations marked as (rare) have kanji_meaning fields that are just a straight copy-paste of the kanjis field without any actual additional info on the kanji.
～までに
ろうそく
ためる
ただ
それで
これから
かしこまりました
ける
おごる
いじめる
ひげ
ひげをそる
すごい
しゃべる
ごみ
The following have meanings for some kanji, but not all:
ヨーロッパ
びっくりする
とにかく
ごちそうする
このぐらい
こちら
みかん

**Comment by mi-ael** [comment]
Thanks! I'll fix them in a few days.

**Comment by mi-ael** [comment]
Finaly got around fixing those. Thanks again and sorry for the delay.

about the Kanji-meanings: I use the wanikani database for the meanings of the kanji. If wanikani has no data about the kanji they are most likely rarely used kanji anyway. Maybe I should hide the meaning field in that case or just remove the kanji altogether. I'll think about it when I have a bit more time.
